// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OffshoreManagementSystem.Infrastructure.DataContext;

#nullable disable

namespace OffsureManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826132000_UserEmailUniqueActiveOnly")]
    partial class UserEmailUniqueActiveOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Current model is tracked in ApplicationDbContextModelSnapshot.
        }
    }
}
