/** Legacy translation-key → route map used by page-header for string crumbs */
export const BREADCRUMB_ROUTES: Record<string, string> = {
  Admin: '/admin/dashboard',
  Client: '/client/dashboard',
  Team: '/team/dashboard',
  Dashboard: '/admin/dashboard',
  Requests: '/admin/requests',
  Projects: '/admin/projects',
  'Project Details': '/admin/projects',
  'Admin Team': '/admin/team',
  Services: '/admin/services',
  Skills: '/admin/skills',
  Portfolio: '/admin/portfolio',
  Companies: '/admin/companies',
  Clients: '/admin/companies',
  Profile: '/client/profile',
  'My Profile': '/admin/profile',
  'My Requests': '/client/requests',
  'My Projects': '/client/projects',
  'New Request': '/client/requests',
  'CUSTOMER.HOME': '/customer/home',
  'ADMIN.DASHBOARD': '/admin/dashboard',
  'MENU.BATCHES': '/customer/batch/list',
  'MENU.CUSTOMERS': '/admin/customers',
  'ADMIN.PORTAL': '/admin/customers',
  'ADMIN.CUSTOMERS_TITLE': '/admin/customers',
  'OPS.TITLE': '/ops/dashboard',
  'OPS.DASHBOARD': '/ops/dashboard',
  'OPS.BATCHES': '/ops/batches',
  'OPS.DEAD_LETTER': '/ops/dead-letter',
  'OPS.RECONCILIATION': '/ops/reconciliation',
};
